[build]
  functions = "api"
  publish = "."

[[redirects]]
  # This keeps your external URL as /proxy
  from = "/proxy"
  # This points it to your new api/netlify.js file
  to = "/.netlify/functions/netlify"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
